# Generated by Django 4.2.6 on 2023-12-28 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userbankaccount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbankaccount',
            old_name='initial_deposite_date',
            new_name='inititial_depose_date',
        ),
    ]
